### ISSUE TITLE
Add homebrew cask installation

### ISSUE THREAD

**Issue by lukasoppermann** [rsodre/QuickLookASE#1]
Hey @rsodre,

it would be awesome if you could make this plugin available via home brew cask: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by vitorgalvao** [comment]
#2.

**Comment by rsodre** [comment]
As soon as I get it to cask I'll update the readme

**Comment by vitorgalvao** [comment]
[It’s already in HBC](https://github.com/caskroom/homebrew-cask/pull/24962) (I’m a maintainer).

**Comment by rsodre** [comment]
Cool, thanks!
